# Generated by Django 4.2.2 on 2023-06-18 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_profile_followers_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
