# Generated by Django 4.2.2 on 2023-06-18 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialfeed', '0004_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
