# Generated by Django 4.1.5 on 2023-06-27 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_userprofile_id_alter_userprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='followers',
        ),
    ]
