# Generated by Django 4.1.5 on 2023-07-08 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialfeed', '0005_delete_profile'),
        ('socialfeed', '0010_message'),
    ]

    operations = [
    ]
